from flask import send_file, request
from datetime import date
from modules.student_attendance import student_attendance_bp
from modules.student_attendance.pdf_utils import generate_pdf
from modules.student_attendance.services import get_daily_management_report
from modules.student_attendance.monthly_report_services import (
    get_previous_month_range,
    monthly_attendance_summary
)
from modules.student_attendance.yearly_report_services import yearly_attendance_summary
import os


BASE_PATH = "runtime_exports"


# ==================================================
# DAILY PDF
# ==================================================

@student_attendance_bp.route("/export/daily-pdf")
def export_daily_pdf():
    att_date = request.args.get("date", date.today().isoformat())
    data = get_daily_management_report(date.fromisoformat(att_date))

    table = [["Class", "Block", "Slot", "Status", "Total"]]
    for r in data:
        table.append([r["class"], r["block"], r["slot"], r["status"], r["total"]])

    file_path = f"{BASE_PATH}/daily_attendance_{att_date}.pdf"

    generate_pdf(
        file_path,
        "Daily Attendance Report",
        f"Date: {att_date}",
        table,
        "Generated by HostelERP"
    )

    return send_file(file_path, as_attachment=True)


# ==================================================
# MONTHLY PDF
# ==================================================

@student_attendance_bp.route("/export/monthly-pdf")
def export_monthly_pdf():
    start = request.args.get("start")
    end = request.args.get("end")

    if start and end:
        start = date.fromisoformat(start)
        end = date.fromisoformat(end)
    else:
        start, end = get_previous_month_range()

    data = monthly_attendance_summary(start, end)

    table = [["Class", "Block", "Total", "Present", "Attendance %", "Gatepass"]]
    for r in data:
        percent = round((r["present"] / r["total"]) * 100, 2) if r["total"] else 0
        table.append([
            r["class"], r["block"], r["total"],
            r["present"], f"{percent}%", r["gatepass"]
        ])

    file_path = f"{BASE_PATH}/monthly_attendance_{start}_{end}.pdf"

    generate_pdf(
        file_path,
        "Monthly Attendance Report",
        f"Period: {start} to {end}",
        table,
        "Prepared by Hostel Superintendent"
    )

    return send_file(file_path, as_attachment=True)


# ==================================================
# YEARLY PDF
# ==================================================

@student_attendance_bp.route("/export/yearly-pdf")
def export_yearly_pdf():
    year = int(request.args.get("year", date.today().year))
    data = yearly_attendance_summary(year)

    table = [["Month", "Total Records", "Present", "Attendance %"]]
    for r in data:
        percent = round((r["present"] / r["total"]) * 100, 2) if r["total"] else 0
        table.append([r["month"], r["total"], r["present"], f"{percent}%"])

    file_path = f"{BASE_PATH}/yearly_attendance_{year}.pdf"

    generate_pdf(
        file_path,
        "Yearly Attendance Report",
        f"Academic Year: {year}",
        table,
        "HostelERP – Management Analytics"
    )

    return send_file(file_path, as_attachment=True)
